
import { Medicine, MedicineCategory } from './types';

// Helper to generate dynamic dates
const getFutureDate = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

export const MEDICINES: Medicine[] = [
  // --- FEVER & PAIN (1-5) ---
  {
    id: 'med_01',
    name: 'Paracetamol 650mg',
    brandExample: 'Dolo 650',
    saltComposition: 'Paracetamol IP 650mg',
    batchNumber: 'PCM-2301',
    stripSize: 15,
    category: MedicineCategory.FEVER,
    commonUse: ['Fever', 'Body Ache', 'Headache'],
    description: 'First-line antipyretic and analgesic for fever and mild pain.',
    genericPrice: 12.00,
    brandedPrice: 33.00,
    stock: 500,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 tab every 6-8 hrs.', maxSafe: '4g/day.', overdoseWarning: 'Liver failure.' },
    details: { mechanism: 'Inhibits COX enzymes.', sideEffects: ['Nausea'], contraindications: ['Liver disease'], storage: 'Cool dry place.' },
  },
  {
    id: 'med_02',
    name: 'Aceclofenac + Paracetamol',
    brandExample: 'Zerodol-P',
    saltComposition: 'Aceclofenac 100mg + Paracetamol 325mg',
    batchNumber: 'ACP-992',
    stripSize: 10,
    category: MedicineCategory.PAIN,
    commonUse: ['Joint Pain', 'Muscle Pain', 'Arthritis'],
    description: 'Combination NSAID for relief from severe pain and inflammation.',
    genericPrice: 22.00,
    brandedPrice: 65.00,
    stock: 200,
    expiryDate: getFutureDate(400),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Twice daily after food.', maxSafe: 'As prescribed.', overdoseWarning: 'Stomach bleeding.' },
    details: { mechanism: 'Reduces pain signals.', sideEffects: ['Heartburn', 'Dizziness'], contraindications: ['Ulcers'], storage: 'Room temp.' },
  },
  {
    id: 'med_03',
    name: 'Ibuprofen 400mg',
    brandExample: 'Brufen 400',
    saltComposition: 'Ibuprofen IP 400mg',
    batchNumber: 'IBU-X1',
    stripSize: 15,
    category: MedicineCategory.PAIN,
    commonUse: ['Inflammation', 'Dental Pain', 'Period Pain'],
    description: 'NSAID used for reducing pain, fever, and inflammation.',
    genericPrice: 15.00,
    brandedPrice: 30.00,
    stock: 150,
    expiryDate: getFutureDate(200),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 tab thrice daily.', maxSafe: '1200mg/day.', overdoseWarning: 'Kidney damage.' },
    details: { mechanism: 'Blocks prostaglandins.', sideEffects: ['Gastritis'], contraindications: ['Asthma'], storage: 'Cool dry place.' },
  },
  {
    id: 'med_04',
    name: 'Diclofenac Gel',
    brandExample: 'Volini Gel',
    saltComposition: 'Diclofenac Diethylamine 1.16%',
    batchNumber: 'DIC-GEL',
    stripSize: 1,
    category: MedicineCategory.PAIN,
    commonUse: ['Back Pain', 'Sprains', 'Neck Pain'],
    description: 'Topical pain relief gel for quick absorption.',
    genericPrice: 45.00,
    brandedPrice: 140.00,
    stock: 100,
    expiryDate: getFutureDate(500),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800', // Using generic medical image
    dosage: { normal: 'Apply 3-4 times daily.', maxSafe: 'External only.', overdoseWarning: 'Skin irritation.' },
    details: { mechanism: 'Local anti-inflammatory.', sideEffects: ['Rash'], contraindications: ['Broken skin'], storage: 'Room temp.' },
  },
  {
    id: 'med_05',
    name: 'Mefenamic Acid 500mg',
    brandExample: 'Meftal 500',
    saltComposition: 'Mefenamic Acid IP 500mg',
    batchNumber: 'MEF-500',
    stripSize: 10,
    category: MedicineCategory.PAIN,
    commonUse: ['Menstrual Cramps', 'Muscle Pain'],
    description: 'Effective for relieving period pain and muscle spasms.',
    genericPrice: 20.00,
    brandedPrice: 45.00,
    stock: 120,
    expiryDate: getFutureDate(300),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 tab thrice daily.', maxSafe: 'Short term.', overdoseWarning: 'Seizures.' },
    details: { mechanism: 'NSAID.', sideEffects: ['Drowsiness'], contraindications: ['Epilepsy'], storage: 'Dry place.' },
  },

  // --- ANTIBIOTICS (6-10) ---
  {
    id: 'med_06',
    name: 'Amoxycillin + Clavulanic Acid',
    brandExample: 'Augmentin 625',
    saltComposition: 'Amoxycillin 500mg + Clavulanic Acid 125mg',
    batchNumber: 'AMC-625',
    stripSize: 6,
    category: MedicineCategory.ANTIBIOTIC,
    commonUse: ['Bacterial Infections', 'Pneumonia', 'Ear Infection'],
    description: 'Broad-spectrum antibiotic for resistant bacteria.',
    genericPrice: 85.00,
    brandedPrice: 205.00,
    stock: 300,
    expiryDate: getFutureDate(180),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2d5f926?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Twice daily for 5-7 days.', maxSafe: 'As prescribed.', overdoseWarning: 'Liver toxicity.' },
    details: { mechanism: 'Kills bacteria.', sideEffects: ['Diarrhea'], contraindications: ['Penicillin allergy'], storage: 'Cool place.' },
  },
  {
    id: 'med_07',
    name: 'Azithromycin 500mg',
    brandExample: 'Azithral 500',
    saltComposition: 'Azithromycin IP 500mg',
    batchNumber: 'AZI-500',
    stripSize: 5,
    category: MedicineCategory.ANTIBIOTIC,
    commonUse: ['Throat Infection', 'Typhoid'],
    description: 'Effective for respiratory and throat infections. 3-day course.',
    genericPrice: 55.00,
    brandedPrice: 120.00,
    stock: 250,
    expiryDate: getFutureDate(20), // Short expiry demo
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 daily for 3 days.', maxSafe: 'As prescribed.', overdoseWarning: 'Heart rhythm issues.' },
    details: { mechanism: 'Stops bacterial growth.', sideEffects: ['Nausea'], contraindications: ['Liver issues'], storage: 'Room temp.' },
  },
  {
    id: 'med_08',
    name: 'Cefixime 200mg',
    brandExample: 'Taxim-O 200',
    saltComposition: 'Cefixime IP 200mg',
    batchNumber: 'CEF-200',
    stripSize: 10,
    category: MedicineCategory.ANTIBIOTIC,
    commonUse: ['UTI', 'Typhoid', 'Bronchitis'],
    description: 'Cephalosporin antibiotic for various bacterial infections.',
    genericPrice: 60.00,
    brandedPrice: 160.00,
    stock: 180,
    expiryDate: getFutureDate(450),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Twice daily.', maxSafe: '400mg/day.', overdoseWarning: 'Kidney stress.' },
    details: { mechanism: 'Cell wall synthesis inhibitor.', sideEffects: ['Gas'], contraindications: ['Cephalosporin allergy'], storage: 'Dry place.' },
  },
  {
    id: 'med_09',
    name: 'Metronidazole 400mg',
    brandExample: 'Flagyl 400',
    saltComposition: 'Metronidazole IP 400mg',
    batchNumber: 'MTZ-400',
    stripSize: 15,
    category: MedicineCategory.ANTIBIOTIC,
    commonUse: ['Stomach Infection', 'Dental Abscess'],
    description: 'Antibiotic and antiprotozoal medication.',
    genericPrice: 12.00,
    brandedPrice: 28.00,
    stock: 400,
    expiryDate: getFutureDate(600),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Thrice daily.', maxSafe: 'As prescribed.', overdoseWarning: 'Nerve damage.' },
    details: { mechanism: 'DNA damage to bacteria.', sideEffects: ['Metallic taste'], contraindications: ['Alcohol'], storage: 'Room temp.' },
  },
  {
    id: 'med_10',
    name: 'Doxycycline 100mg',
    brandExample: 'Doxy-1',
    saltComposition: 'Doxycycline IP 100mg',
    batchNumber: 'DOX-100',
    stripSize: 10,
    category: MedicineCategory.ANTIBIOTIC,
    commonUse: ['Acne', 'Respiratory Infection'],
    description: 'Tetracycline antibiotic used for skin and chest infections.',
    genericPrice: 25.00,
    brandedPrice: 85.00,
    stock: 90,
    expiryDate: getFutureDate(300),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Twice daily.', maxSafe: 'As prescribed.', overdoseWarning: 'Liver stress.' },
    details: { mechanism: 'Protein synthesis inhibitor.', sideEffects: ['Sun sensitivity'], contraindications: ['Pregnancy'], storage: 'Dark place.' },
  },

  // --- DIABETES (11-15) ---
  {
    id: 'med_11',
    name: 'Metformin 500mg',
    brandExample: 'Glycomet 500',
    saltComposition: 'Metformin IP 500mg',
    batchNumber: 'MET-500',
    stripSize: 10,
    category: MedicineCategory.DIABETES,
    commonUse: ['Type 2 Diabetes'],
    description: 'First-line medication for blood sugar control.',
    genericPrice: 15.00,
    brandedPrice: 38.00,
    stock: 600,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'With meals.', maxSafe: '2000mg/day.', overdoseWarning: 'Lactic acidosis.' },
    details: { mechanism: 'Improves insulin sensitivity.', sideEffects: ['Bloating'], contraindications: ['Kidney failure'], storage: 'Room temp.' },
  },
  {
    id: 'med_12',
    name: 'Glimepiride 1mg',
    brandExample: 'Amaryl 1mg',
    saltComposition: 'Glimepiride IP 1mg',
    batchNumber: 'GLM-01',
    stripSize: 15,
    category: MedicineCategory.DIABETES,
    commonUse: ['Type 2 Diabetes'],
    description: 'Stimulates pancreas to release insulin.',
    genericPrice: 18.00,
    brandedPrice: 90.00,
    stock: 200,
    expiryDate: getFutureDate(400),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily before breakfast.', maxSafe: '8mg/day.', overdoseWarning: 'Hypoglycemia.' },
    details: { mechanism: 'Insulin release.', sideEffects: ['Low blood sugar'], contraindications: ['Type 1 Diabetes'], storage: 'Room temp.' },
  },
  {
    id: 'med_13',
    name: 'Vildagliptin 50mg',
    brandExample: 'Galvus 50',
    saltComposition: 'Vildagliptin 50mg',
    batchNumber: 'VIL-50',
    stripSize: 14,
    category: MedicineCategory.DIABETES,
    commonUse: ['Type 2 Diabetes'],
    description: 'DPP-4 inhibitor for post-meal sugar spikes.',
    genericPrice: 65.00,
    brandedPrice: 220.00,
    stock: 150,
    expiryDate: getFutureDate(500),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Twice daily.', maxSafe: '100mg/day.', overdoseWarning: 'Liver stress.' },
    details: { mechanism: 'Increases incretins.', sideEffects: ['Tremors'], contraindications: ['Liver disease'], storage: 'Room temp.' },
  },
  {
    id: 'med_14',
    name: 'Sitagliptin 100mg',
    brandExample: 'Januvia 100',
    saltComposition: 'Sitagliptin 100mg',
    batchNumber: 'SIT-100',
    stripSize: 7,
    category: MedicineCategory.DIABETES,
    commonUse: ['Type 2 Diabetes'],
    description: 'Once-daily medicine for stable sugar control.',
    genericPrice: 70.00,
    brandedPrice: 240.00,
    stock: 80,
    expiryDate: getFutureDate(250),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2d5f926?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily.', maxSafe: '100mg/day.', overdoseWarning: 'Pancreatitis.' },
    details: { mechanism: 'DPP-4 inhibitor.', sideEffects: ['Joint pain'], contraindications: ['Pancreatitis'], storage: 'Dry place.' },
  },
  {
    id: 'med_15',
    name: 'Gliclazide 80mg',
    brandExample: 'Reclide 80',
    saltComposition: 'Gliclazide 80mg',
    batchNumber: 'GLI-80',
    stripSize: 10,
    category: MedicineCategory.DIABETES,
    commonUse: ['Type 2 Diabetes'],
    description: 'Sulfonylurea class medicine for diabetes.',
    genericPrice: 35.00,
    brandedPrice: 95.00,
    stock: 110,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'With breakfast.', maxSafe: 'As prescribed.', overdoseWarning: 'Hypoglycemia.' },
    details: { mechanism: 'Insulin secretion.', sideEffects: ['Weight gain'], contraindications: ['Severe liver/kidney issues'], storage: 'Room temp.' },
  },

  // --- HEART & BP (16-22) ---
  {
    id: 'med_16',
    name: 'Amlodipine 5mg',
    brandExample: 'Amlong 5',
    saltComposition: 'Amlodipine 5mg',
    batchNumber: 'AML-05',
    stripSize: 15,
    category: MedicineCategory.HEART,
    commonUse: ['Hypertension', 'Angina'],
    description: 'Calcium channel blocker to lower blood pressure.',
    genericPrice: 10.00,
    brandedPrice: 45.00,
    stock: 400,
    expiryDate: getFutureDate(600),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily.', maxSafe: '10mg/day.', overdoseWarning: 'Low BP.' },
    details: { mechanism: 'Relaxes blood vessels.', sideEffects: ['Swollen ankles'], contraindications: ['Heart failure'], storage: 'Room temp.' },
  },
  {
    id: 'med_17',
    name: 'Telmisartan 40mg',
    brandExample: 'Telma 40',
    saltComposition: 'Telmisartan 40mg',
    batchNumber: 'TEL-40',
    stripSize: 15,
    category: MedicineCategory.HEART,
    commonUse: ['High BP', 'Heart Failure prevention'],
    description: 'ARB medicine widely used for BP control.',
    genericPrice: 25.00,
    brandedPrice: 110.00,
    stock: 350,
    expiryDate: getFutureDate(400),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily.', maxSafe: '80mg/day.', overdoseWarning: 'Dizziness.' },
    details: { mechanism: 'Blocks angiotensin.', sideEffects: ['Dizziness'], contraindications: ['Pregnancy'], storage: 'Dry place.' },
  },
  {
    id: 'med_18',
    name: 'Atorvastatin 10mg',
    brandExample: 'Atorva 10',
    saltComposition: 'Atorvastatin 10mg',
    batchNumber: 'ATO-10',
    stripSize: 15,
    category: MedicineCategory.HEART,
    commonUse: ['High Cholesterol', 'Heart Attack prevention'],
    description: 'Statin to lower bad cholesterol.',
    genericPrice: 20.00,
    brandedPrice: 90.00,
    stock: 300,
    expiryDate: getFutureDate(500),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'At night daily.', maxSafe: 'As prescribed.', overdoseWarning: 'Muscle damage.' },
    details: { mechanism: 'Blocks cholesterol enzyme.', sideEffects: ['Muscle pain'], contraindications: ['Liver disease'], storage: 'Room temp.' },
  },
  {
    id: 'med_19',
    name: 'Rosuvastatin 10mg',
    brandExample: 'Rosuvas 10',
    saltComposition: 'Rosuvastatin 10mg',
    batchNumber: 'ROS-10',
    stripSize: 10,
    category: MedicineCategory.HEART,
    commonUse: ['High Cholesterol'],
    description: 'Potent statin for reducing lipid levels.',
    genericPrice: 35.00,
    brandedPrice: 145.00,
    stock: 150,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily.', maxSafe: '40mg/day.', overdoseWarning: 'Kidney issues.' },
    details: { mechanism: 'Lipid lowering.', sideEffects: ['Headache'], contraindications: ['Active liver disease'], storage: 'Dry place.' },
  },
  {
    id: 'med_20',
    name: 'Clopidogrel 75mg',
    brandExample: 'Plavix 75',
    saltComposition: 'Clopidogrel 75mg',
    batchNumber: 'CLP-75',
    stripSize: 15,
    category: MedicineCategory.HEART,
    commonUse: ['Blood Thinner', 'Stroke Prevention'],
    description: 'Antiplatelet medicine to prevent clots.',
    genericPrice: 40.00,
    brandedPrice: 130.00,
    stock: 200,
    expiryDate: getFutureDate(600),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily.', maxSafe: 'As prescribed.', overdoseWarning: 'Bleeding.' },
    details: { mechanism: 'Prevents platelet aggregation.', sideEffects: ['Bruising'], contraindications: ['Active bleeding'], storage: 'Room temp.' },
  },
  {
    id: 'med_21',
    name: 'Propranolol 40mg',
    brandExample: 'Ciplar 40',
    saltComposition: 'Propranolol 40mg',
    batchNumber: 'PRO-40',
    stripSize: 15,
    category: MedicineCategory.HEART,
    commonUse: ['Anxiety', 'Migraine', 'Tremors'],
    description: 'Beta-blocker used for heart and anxiety issues.',
    genericPrice: 15.00,
    brandedPrice: 55.00,
    stock: 180,
    expiryDate: getFutureDate(400),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2d5f926?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Twice daily.', maxSafe: 'As prescribed.', overdoseWarning: 'Slow heart rate.' },
    details: { mechanism: 'Blocks beta receptors.', sideEffects: ['Fatigue'], contraindications: ['Asthma'], storage: 'Cool place.' },
  },
  {
    id: 'med_22',
    name: 'Losartan 50mg',
    brandExample: 'Losar 50',
    saltComposition: 'Losartan 50mg',
    batchNumber: 'LOS-50',
    stripSize: 15,
    category: MedicineCategory.HEART,
    commonUse: ['High BP'],
    description: 'ARB medicine for blood pressure control.',
    genericPrice: 22.00,
    brandedPrice: 85.00,
    stock: 220,
    expiryDate: getFutureDate(450),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily.', maxSafe: '100mg/day.', overdoseWarning: 'Low BP.' },
    details: { mechanism: 'Vasodilation.', sideEffects: ['Dizziness'], contraindications: ['Pregnancy'], storage: 'Dry place.' },
  },

  // --- ACIDITY & DIGESTIVE (23-29) ---
  {
    id: 'med_23',
    name: 'Pantoprazole 40mg',
    brandExample: 'Pan 40',
    saltComposition: 'Pantoprazole 40mg',
    batchNumber: 'PAN-40',
    stripSize: 15,
    category: MedicineCategory.ACIDITY,
    commonUse: ['Acidity', 'GERD', 'Gastritis'],
    description: 'Proton pump inhibitor to reduce stomach acid.',
    genericPrice: 30.00,
    brandedPrice: 155.00,
    stock: 600,
    expiryDate: getFutureDate(500),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Empty stomach morning.', maxSafe: '80mg/day.', overdoseWarning: 'Digestion issues.' },
    details: { mechanism: 'Inhibits acid pump.', sideEffects: ['Headache'], contraindications: ['Low magnesium'], storage: 'Room temp.' },
  },
  {
    id: 'med_24',
    name: 'Omeprazole 20mg',
    brandExample: 'Omez',
    saltComposition: 'Omeprazole 20mg',
    batchNumber: 'OME-20',
    stripSize: 20,
    category: MedicineCategory.ACIDITY,
    commonUse: ['Heartburn', 'Ulcers'],
    description: 'Classic acid reducer for stomach issues.',
    genericPrice: 25.00,
    brandedPrice: 80.00,
    stock: 500,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Before breakfast.', maxSafe: 'As prescribed.', overdoseWarning: 'Nausea.' },
    details: { mechanism: 'PPI.', sideEffects: ['Gas'], contraindications: ['Liver disease'], storage: 'Dry place.' },
  },
  {
    id: 'med_25',
    name: 'Rabeprazole 20mg',
    brandExample: 'Razo 20',
    saltComposition: 'Rabeprazole 20mg',
    batchNumber: 'RAB-20',
    stripSize: 15,
    category: MedicineCategory.ACIDITY,
    commonUse: ['Severe Acidity'],
    description: 'Fast-acting PPI for acidity relief.',
    genericPrice: 45.00,
    brandedPrice: 190.00,
    stock: 200,
    expiryDate: getFutureDate(400),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Before food.', maxSafe: 'As prescribed.', overdoseWarning: 'Stomach pain.' },
    details: { mechanism: 'Reduces acid.', sideEffects: ['Diarrhea'], contraindications: ['Hypersensitivity'], storage: 'Room temp.' },
  },
  {
    id: 'med_26',
    name: 'Domperidone 10mg',
    brandExample: 'Domstal',
    saltComposition: 'Domperidone 10mg',
    batchNumber: 'DOM-10',
    stripSize: 10,
    category: MedicineCategory.ACIDITY,
    commonUse: ['Nausea', 'Vomiting', 'Bloating'],
    description: 'Prokinetic agent to improve digestion speed.',
    genericPrice: 15.00,
    brandedPrice: 35.00,
    stock: 250,
    expiryDate: getFutureDate(300),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Before meals.', maxSafe: '30mg/day.', overdoseWarning: 'Heart rhythm.' },
    details: { mechanism: 'Blocks dopamine receptors.', sideEffects: ['Dry mouth'], contraindications: ['Heart issues'], storage: 'Room temp.' },
  },
  {
    id: 'med_27',
    name: 'Ondansetron 4mg',
    brandExample: 'Emeset 4',
    saltComposition: 'Ondansetron 4mg',
    batchNumber: 'OND-04',
    stripSize: 10,
    category: MedicineCategory.ACIDITY,
    commonUse: ['Vomiting', 'Nausea'],
    description: 'Effective anti-emetic for nausea relief.',
    genericPrice: 12.00,
    brandedPrice: 55.00,
    stock: 300,
    expiryDate: getFutureDate(600),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'As needed.', maxSafe: '8mg/dose.', overdoseWarning: 'Constipation.' },
    details: { mechanism: 'Blocks serotonin.', sideEffects: ['Headache'], contraindications: ['Apomorphine use'], storage: 'Dry place.' },
  },
  {
    id: 'med_28',
    name: 'Lactulose Solution',
    brandExample: 'Duphalac',
    saltComposition: 'Lactulose 10g/15ml',
    batchNumber: 'LAC-SYP',
    stripSize: 1,
    category: MedicineCategory.ACIDITY,
    commonUse: ['Constipation'],
    description: 'Laxative syrup for treating constipation.',
    genericPrice: 90.00,
    brandedPrice: 250.00,
    stock: 100,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '15-30ml at night.', maxSafe: 'As prescribed.', overdoseWarning: 'Diarrhea.' },
    details: { mechanism: 'Draws water into bowel.', sideEffects: ['Gas'], contraindications: ['Galactosemia'], storage: 'Room temp.' },
  },
  {
    id: 'med_29',
    name: 'Isabgol Husk',
    brandExample: 'Softovac / Dabur',
    saltComposition: 'Psyllium Husk',
    batchNumber: 'ISA-HUSK',
    stripSize: 1,
    category: MedicineCategory.ACIDITY,
    commonUse: ['Constipation', 'Fiber Supplement'],
    description: 'Natural fiber for healthy digestion.',
    genericPrice: 80.00,
    brandedPrice: 180.00,
    stock: 120,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1-2 spoons with water.', maxSafe: 'N/A', overdoseWarning: 'Bloating.' },
    details: { mechanism: 'Bulk forming laxative.', sideEffects: ['Fullness'], contraindications: ['Bowel obstruction'], storage: 'Dry place.' },
  },

  // --- ALLERGY & COLD (30-33, 38-40) ---
  {
    id: 'med_30',
    name: 'Cetirizine 10mg',
    brandExample: 'Cetzine',
    saltComposition: 'Cetirizine 10mg',
    batchNumber: 'CET-10',
    stripSize: 10,
    category: MedicineCategory.ALLERGY,
    commonUse: ['Sneezing', 'Allergy', 'Itching'],
    description: 'Non-drowsy antihistamine for daily allergy relief.',
    genericPrice: 10.00,
    brandedPrice: 45.00,
    stock: 450,
    expiryDate: getFutureDate(700),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2d5f926?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily at night.', maxSafe: '10mg/day.', overdoseWarning: 'Drowsiness.' },
    details: { mechanism: 'Blocks histamine.', sideEffects: ['Mild sleepiness'], contraindications: ['Kidney failure'], storage: 'Room temp.' },
  },
  {
    id: 'med_31',
    name: 'Montelukast + Levocetirizine',
    brandExample: 'Montek-LC',
    saltComposition: 'Montelukast 10mg + Levocetirizine 5mg',
    batchNumber: 'MNT-LC',
    stripSize: 10,
    category: MedicineCategory.COLD_FLU,
    commonUse: ['Allergic Rhinitis', 'Asthma'],
    description: 'Combination for blocked nose and allergy.',
    genericPrice: 40.00,
    brandedPrice: 160.00,
    stock: 200,
    expiryDate: getFutureDate(400),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily at night.', maxSafe: '1 tab/day.', overdoseWarning: 'Dizziness.' },
    details: { mechanism: 'Reduces airway inflammation.', sideEffects: ['Dry mouth'], contraindications: ['Liver disease'], storage: 'Dry place.' },
  },
  {
    id: 'med_32',
    name: 'Fexofenadine 120mg',
    brandExample: 'Allegra 120',
    saltComposition: 'Fexofenadine 120mg',
    batchNumber: 'FEX-120',
    stripSize: 10,
    category: MedicineCategory.ALLERGY,
    commonUse: ['Skin Allergy', 'Hives'],
    description: 'Non-sedative antihistamine for skin allergies.',
    genericPrice: 60.00,
    brandedPrice: 180.00,
    stock: 150,
    expiryDate: getFutureDate(500),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily.', maxSafe: '180mg/day.', overdoseWarning: 'Headache.' },
    details: { mechanism: 'Histamine blocker.', sideEffects: ['Nausea'], contraindications: ['Kidney disease'], storage: 'Room temp.' },
  },
  {
    id: 'med_33',
    name: 'Phenylephrine + CPM',
    brandExample: 'Maxtra / Sinarest',
    saltComposition: 'Phenylephrine + Chlorpheniramine',
    batchNumber: 'COLD-TAB',
    stripSize: 10,
    category: MedicineCategory.COLD_FLU,
    commonUse: ['Common Cold', 'Congestion'],
    description: 'Relief from runny nose and nasal congestion.',
    genericPrice: 20.00,
    brandedPrice: 60.00,
    stock: 300,
    expiryDate: getFutureDate(300),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Twice daily.', maxSafe: 'Thrice daily.', overdoseWarning: 'High BP.' },
    details: { mechanism: 'Decongestant.', sideEffects: ['Sleepiness'], contraindications: ['Hypertension'], storage: 'Cool place.' },
  },

  // --- SUPPLEMENTS & THYROID (34-37, 40-42) ---
  {
    id: 'med_34',
    name: 'Calcium + Vitamin D3',
    brandExample: 'Shelcal 500',
    saltComposition: 'Calcium 500mg + Vit D3 250IU',
    batchNumber: 'CAL-D3',
    stripSize: 15,
    category: MedicineCategory.SUPPLEMENTS,
    commonUse: ['Bone Health', 'Osteoporosis'],
    description: 'Essential supplement for strong bones.',
    genericPrice: 40.00,
    brandedPrice: 125.00,
    stock: 400,
    expiryDate: getFutureDate(500),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily.', maxSafe: 'Consult doctor.', overdoseWarning: 'Kidney stones.' },
    details: { mechanism: 'Calcium absorption.', sideEffects: ['Gas'], contraindications: ['Hypercalcemia'], storage: 'Dry place.' },
  },
  {
    id: 'med_35',
    name: 'Vitamin B Complex',
    brandExample: 'Becosules',
    saltComposition: 'B-Complex + Vit C',
    batchNumber: 'B-COM',
    stripSize: 20,
    category: MedicineCategory.SUPPLEMENTS,
    commonUse: ['Mouth Ulcers', 'Immunity'],
    description: 'Daily multivitamin for energy and mouth health.',
    genericPrice: 18.00,
    brandedPrice: 45.00,
    stock: 500,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 daily.', maxSafe: 'N/A', overdoseWarning: 'Bright urine.' },
    details: { mechanism: 'Nutrient support.', sideEffects: ['None'], contraindications: ['None'], storage: 'Cool place.' },
  },
  {
    id: 'med_36',
    name: 'Vitamin C 500mg',
    brandExample: 'Limcee',
    saltComposition: 'Ascorbic Acid 500mg',
    batchNumber: 'VIT-C',
    stripSize: 15,
    category: MedicineCategory.SUPPLEMENTS,
    commonUse: ['Immunity', 'Skin Health'],
    description: 'Chewable vitamin C for immunity boost.',
    genericPrice: 15.00,
    brandedPrice: 25.00,
    stock: 350,
    expiryDate: getFutureDate(600),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 daily.', maxSafe: '1000mg/day.', overdoseWarning: 'Stomach upset.' },
    details: { mechanism: 'Antioxidant.', sideEffects: ['Acidity'], contraindications: ['None'], storage: 'Room temp.' },
  },
  {
    id: 'med_37',
    name: 'Iron + Folic Acid',
    brandExample: 'Orofer XT',
    saltComposition: 'Ferrous Ascorbate + Folic Acid',
    batchNumber: 'IRON-XT',
    stripSize: 10,
    category: MedicineCategory.SUPPLEMENTS,
    commonUse: ['Anemia', 'Hemoglobin'],
    description: 'Iron supplement for low hemoglobin.',
    genericPrice: 50.00,
    brandedPrice: 140.00,
    stock: 150,
    expiryDate: getFutureDate(400),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2d5f926?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'After food.', maxSafe: 'As prescribed.', overdoseWarning: 'Dark stools.' },
    details: { mechanism: 'Blood formation.', sideEffects: ['Constipation'], contraindications: ['Thalassemia'], storage: 'Dry place.' },
  },
  {
    id: 'med_38',
    name: 'Salbutamol Inhaler',
    brandExample: 'Asthalin',
    saltComposition: 'Salbutamol 100mcg',
    batchNumber: 'INHAL-01',
    stripSize: 1,
    category: MedicineCategory.COLD_FLU,
    commonUse: ['Asthma', 'Breathlessness'],
    description: 'Rescue inhaler for immediate relief.',
    genericPrice: 80.00,
    brandedPrice: 160.00,
    stock: 100,
    expiryDate: getFutureDate(700),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=800', // Inhaler image placeholder
    dosage: { normal: '2 puffs SOS.', maxSafe: 'As needed.', overdoseWarning: 'Shaking hands.' },
    details: { mechanism: 'Bronchodilator.', sideEffects: ['Tremors'], contraindications: ['None'], storage: 'Room temp.' },
  },
  {
    id: 'med_39',
    name: 'Budesonide Respules',
    brandExample: 'Budecort',
    saltComposition: 'Budesonide 0.5mg',
    batchNumber: 'BUD-RESP',
    stripSize: 5,
    category: MedicineCategory.COLD_FLU,
    commonUse: ['Severe Asthma', 'Nebulization'],
    description: 'Steroid neb-solution for lung inflammation.',
    genericPrice: 40.00,
    brandedPrice: 120.00,
    stock: 80,
    expiryDate: getFutureDate(300),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'As prescribed.', maxSafe: 'N/A', overdoseWarning: 'Thrush.' },
    details: { mechanism: 'Anti-inflammatory.', sideEffects: ['Throat irritation'], contraindications: ['TB'], storage: 'Cool place.' },
  },
  {
    id: 'med_40',
    name: 'Levosalbutamol Syrup',
    brandExample: 'Asthalin LS',
    saltComposition: 'Levosalbutamol',
    batchNumber: 'LEV-SYP',
    stripSize: 1,
    category: MedicineCategory.COLD_FLU,
    commonUse: ['Cough', 'Bronchitis'],
    description: 'Syrup for productive cough and breathing.',
    genericPrice: 35.00,
    brandedPrice: 95.00,
    stock: 120,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '5-10ml thrice.', maxSafe: 'As prescribed.', overdoseWarning: 'Palpitations.' },
    details: { mechanism: 'Opens airways.', sideEffects: ['High heart rate'], contraindications: ['Heart disease'], storage: 'Room temp.' },
  },
  {
    id: 'med_41',
    name: 'Thyroxine 50mcg',
    brandExample: 'Thyronorm 50',
    saltComposition: 'Thyroxine Sodium 50mcg',
    batchNumber: 'THY-50',
    stripSize: 100,
    category: MedicineCategory.THYROID,
    commonUse: ['Hypothyroidism'],
    description: 'Thyroid hormone replacement therapy.',
    genericPrice: 60.00,
    brandedPrice: 130.00,
    stock: 200,
    expiryDate: getFutureDate(500),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Empty stomach daily.', maxSafe: 'As prescribed.', overdoseWarning: 'Palpitations.' },
    details: { mechanism: 'Hormone replacement.', sideEffects: ['Weight loss'], contraindications: ['Thyrotoxicosis'], storage: 'Dark place.' },
  },
  {
    id: 'med_42',
    name: 'Thyroxine 100mcg',
    brandExample: 'Thyronorm 100',
    saltComposition: 'Thyroxine Sodium 100mcg',
    batchNumber: 'THY-100',
    stripSize: 100,
    category: MedicineCategory.THYROID,
    commonUse: ['Hypothyroidism'],
    description: 'Higher dose thyroid supplement.',
    genericPrice: 90.00,
    brandedPrice: 180.00,
    stock: 150,
    expiryDate: getFutureDate(500),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Empty stomach daily.', maxSafe: 'As prescribed.', overdoseWarning: 'Tremors.' },
    details: { mechanism: 'Hormone replacement.', sideEffects: ['Sweating'], contraindications: ['Thyrotoxicosis'], storage: 'Dark place.' },
  },

  // --- SKIN (43-45) ---
  {
    id: 'med_43',
    name: 'Clotrimazole Cream',
    brandExample: 'Candid',
    saltComposition: 'Clotrimazole 1%',
    batchNumber: 'CLT-CRM',
    stripSize: 1,
    category: MedicineCategory.SKIN,
    commonUse: ['Fungal Infection', 'Ringworm'],
    description: 'Topical antifungal cream.',
    genericPrice: 20.00,
    brandedPrice: 85.00,
    stock: 200,
    expiryDate: getFutureDate(600),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Apply twice daily.', maxSafe: 'External only.', overdoseWarning: 'Irritation.' },
    details: { mechanism: 'Kills fungus.', sideEffects: ['Burning'], contraindications: ['None'], storage: 'Cool place.' },
  },
  {
    id: 'med_44',
    name: 'Permethrin Lotion',
    brandExample: 'Permite',
    saltComposition: 'Permethrin 5%',
    batchNumber: 'PER-LOT',
    stripSize: 1,
    category: MedicineCategory.SKIN,
    commonUse: ['Scabies'],
    description: 'Anti-parasitic lotion for scabies.',
    genericPrice: 40.00,
    brandedPrice: 90.00,
    stock: 50,
    expiryDate: getFutureDate(400),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Apply neck down once.', maxSafe: 'One time use.', overdoseWarning: 'Skin rash.' },
    details: { mechanism: 'Paralyzes mites.', sideEffects: ['Itching'], contraindications: ['Broken skin'], storage: 'Room temp.' },
  },
  {
    id: 'med_45',
    name: 'Minoxidil 5%',
    brandExample: 'Mintop 5',
    saltComposition: 'Minoxidil 5%',
    batchNumber: 'MIN-05',
    stripSize: 1,
    category: MedicineCategory.SKIN,
    commonUse: ['Hair Loss', 'Alopecia'],
    description: 'Solution to promote hair regrowth.',
    genericPrice: 200.00,
    brandedPrice: 650.00,
    stock: 80,
    expiryDate: getFutureDate(365),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1ml twice daily.', maxSafe: 'External.', overdoseWarning: 'Low BP.' },
    details: { mechanism: 'Increases blood flow.', sideEffects: ['Itching'], contraindications: ['Heart disease'], storage: 'Room temp.' },
  },

  // --- NEURO & WOMEN (46-50) ---
  {
    id: 'med_46',
    name: 'Escitalopram 10mg',
    brandExample: 'Nexito 10',
    saltComposition: 'Escitalopram 10mg',
    batchNumber: 'ESC-10',
    stripSize: 10,
    category: MedicineCategory.NEURO,
    commonUse: ['Anxiety', 'Depression'],
    description: 'SSRI antidepressant for mental wellness.',
    genericPrice: 35.00,
    brandedPrice: 110.00,
    stock: 120,
    expiryDate: getFutureDate(450),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Once daily morning.', maxSafe: '20mg/day.', overdoseWarning: 'Serotonin syndrome.' },
    details: { mechanism: 'Increases serotonin.', sideEffects: ['Nausea'], contraindications: ['MAOIs'], storage: 'Dry place.' },
  },
  {
    id: 'med_47',
    name: 'Gabapentin 300mg',
    brandExample: 'Gabantin 300',
    saltComposition: 'Gabapentin 300mg',
    batchNumber: 'GAB-300',
    stripSize: 10,
    category: MedicineCategory.NEURO,
    commonUse: ['Nerve Pain', 'Neuropathy'],
    description: 'Medicine for nerve pain and seizures.',
    genericPrice: 40.00,
    brandedPrice: 150.00,
    stock: 90,
    expiryDate: getFutureDate(300),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'At night.', maxSafe: 'As prescribed.', overdoseWarning: 'Drowsiness.' },
    details: { mechanism: 'Calms nerves.', sideEffects: ['Sleepiness'], contraindications: ['Kidney issues'], storage: 'Room temp.' },
  },
  {
    id: 'med_48',
    name: 'Clonazepam 0.5mg',
    brandExample: 'Clonotril 0.5',
    saltComposition: 'Clonazepam 0.5mg',
    batchNumber: 'CLO-05',
    stripSize: 10,
    category: MedicineCategory.NEURO,
    commonUse: ['Anxiety', 'Sleep'],
    description: 'Sedative for acute anxiety relief.',
    genericPrice: 15.00,
    brandedPrice: 45.00,
    stock: 100,
    expiryDate: getFutureDate(400),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'At night.', maxSafe: 'Habit forming.', overdoseWarning: 'Deep sleep.' },
    details: { mechanism: 'Calms brain.', sideEffects: ['Sedation'], contraindications: ['Glaucoma'], storage: 'Safe place.' },
  },
  {
    id: 'med_49',
    name: 'Oral Contraceptive Pill',
    brandExample: 'Mala-D / Yasmin',
    saltComposition: 'Ethinylestradiol + Levonorgestrel',
    batchNumber: 'OCP-21',
    stripSize: 21,
    category: MedicineCategory.WOMEN,
    commonUse: ['Birth Control', 'PCOS'],
    description: 'Hormonal tablet for cycle regulation.',
    genericPrice: 5.00,
    brandedPrice: 450.00,
    stock: 300,
    expiryDate: getFutureDate(600),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edbb97aa1976?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: '1 daily for 21 days.', maxSafe: '1/day.', overdoseWarning: 'Nausea.' },
    details: { mechanism: 'Prevents ovulation.', sideEffects: ['Mood swings'], contraindications: ['Clotting history'], storage: 'Dry place.' },
  },
  {
    id: 'med_50',
    name: 'Tranexamic Acid',
    brandExample: 'Texakind',
    saltComposition: 'Tranexamic Acid 500mg',
    batchNumber: 'TRA-500',
    stripSize: 10,
    category: MedicineCategory.WOMEN,
    commonUse: ['Heavy Period Flow'],
    description: 'Controls excessive bleeding.',
    genericPrice: 60.00,
    brandedPrice: 180.00,
    stock: 80,
    expiryDate: getFutureDate(500),
    marketRates: [],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    dosage: { normal: 'Thrice daily during flow.', maxSafe: 'Short term.', overdoseWarning: 'Clotting.' },
    details: { mechanism: 'Helps blood clot.', sideEffects: ['Nausea'], contraindications: ['Active clots'], storage: 'Room temp.' },
  }
];

export const ANIMATIONS = {
    fadeIn: "animate-fade-in",
    slideUp: "animate-slide-up"
};
